# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltExam', '0002_auto_20160624_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poked', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userpoke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='beltExam.User')),
                ('userpoked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='beltExam.User')),
            ],
        ),
    ]
